In [2]:
import pandas as pd
import ast

# Load the dataset
kwt = pd.read_csv('kwt_df.csv')

In [3]:
# checking the first few rows
kwt.head()

,id,location,time,end_time,message,provenance,event_type,priority,priority_label,attributes,...,groupby_col,segment_start,segment_end,timespan_seconds,dist_meters,speed_kmhr,heading,junk_status,extra__hex,extra__name
0,92ab0637-e089-4513-b3b0-b4f7e6dcd788,"{'latitude': -1.493029, 'longitude': 35.58333}",2024-02-05T19:42:00+03:00,NaN,NaN,NaN,hwc_rep,300.0,Red,{},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,68d2609c-b21d-421c-9cf5-b083abdb0703,"{'latitude': -1.13321534764331, 'longitude': 3...",2024-02-07T11:00:00+03:00,NaN,NaN,NaN,hwc_rep,300.0,Red,{},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,9dfc57bd-4718-4b66-9315-2beeb930a46f,"{'latitude': -1.05007, 'longitude': 35.193156}",2024-02-12T02:00:00+03:00,NaN,NaN,NaN,hwc_rep,300.0,Red,{},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,9c3ce49a-cbeb-46c3-8e1b-7cb881de1c79,"{'latitude': -1.530613, 'longitude': 35.543826}",2024-02-12T06:14:00+03:00,NaN,NaN,NaN,hwc_rep,300.0,Red,{},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,eb3bdd59-07c9-42bb-a882-749c538113b7,"{'latitude': -1.530613, 'longitude': 35.543829}",2024-02-12T06:14:00+03:00,NaN,NaN,NaN,hwc_rep,300.0,Red,{},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#checking the last few rows
kwt.tail()

,id,location,time,end_time,message,provenance,event_type,priority,priority_label,attributes,...,groupby_col,segment_start,segment_end,timespan_seconds,dist_meters,speed_kmhr,heading,junk_status,extra__hex,extra__name
10189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,846a0edb-88a9-4646-a7ab-83fe0bdfc554,2024-03-14 20:00:16+00:00,2024-03-14 21:00:13+00:00,3597.0,8.176088,0.008183,164.952978,False,#050505,98659_Samara
10190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23a06ce4-ae0d-41fe-8151-697442ee9f73,2024-03-14 21:00:15+00:00,2024-03-14 22:00:12+00:00,3597.0,9.715274,0.009723,217.720423,False,#07F028,42559_Komeyian
10191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,f564b4e5-f3b1-4f01-becf-f48f366c5965,2024-03-14 22:00:15+00:00,2024-03-14 23:00:12+00:00,3597.0,138.644149,0.138760,171.015963,False,#7D0FF2,42557_Namunyak
10192,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,c4ac27d7-8402-453e-acb4-d4ceb1d29de8,2024-03-14 22:00:37+00:00,2024-03-14 23:00:10+00:00,3573.0,809.731809,0.815851,10.604835,False,#4629E6,98655_Nashipai
10193,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,846a0edb-88a9-4646-a7ab-83fe0bdfc554,2024-03-14 22:00:42+00:00,2024-03-14 23:00:11+00:00,3569.0,0.859215,0.000867,81.175170,False,#050505,98659_Samara

In [5]:
kwt.columns

Index(['id', 'location', 'time', 'end_time', 'message', 'provenance',
       'event_type', 'priority', 'priority_label', 'attributes', 'comment',
       'title', 'state', 'sort_at', 'updated_at', 'created_at', 'icon_id',
       'serial_number', 'event_category', 'url', 'image_url', 'geojson',
       'is_collection', 'event_details__hwcrep_species',
       'event_details__hwcrep_livestocktypes',
       'event_details__hwcrep_livestockInjuredKilled',
       'event_details__hwcrep_humandeath', 'event_details__hwcrep_humaninjury',
       'event_details__hwcrep_cropdamaged', 'reported_by__username',
       'reported_by__first_name', 'reported_by__last_name', 'reported_by__id',
       'reported_by__content_type', 'reported_by__name',
       'reported_by__subject_type', 'reported_by__subject_subtype',
       'reported_by__common_name', 'reported_by__created_at',
       'reported_by__updated_at', 'reported_by__is_active',
       'reported_by__tracks_available', 'reported_by__image_url',
       'reported_by__user__id', 'geometry', 'groupby_col', 'segment_start',
       'segment_end', 'timespan_seconds', 'dist_meters', 'speed_kmhr',
       'heading', 'junk_status', 'extra__hex', 'extra__name'],
      dtype='object')